name: @name@
version: @version@
authors: [ qwz ]
main: @main_class@
description: Logging data based on conditions.
softdepend: [ PlaceholderAPI, Vault, WorldEdit, WorldGuard, Votifier ]
commands:
  milestones:
    aliases: [ mile, miles ]
    description: Main plugin command